### PR TITLE
Switch to test/Project.toml

### PR DESCRIPTION
**Pull request by IanButterworth**

### CODE REVIEW

**Comment by timholy** [comment]
What's the advantage? I can't find it now, but a recent conversation I only skimmed between Shuhei & @KristofferC suggested little advantage (which has been my experience).

**Comment by IanButterworth** [comment]
Well, this was prompted because when I did
```
pkg> test ImageView
```
sometime during test execution it complained about some of the test deps not being installed. I think ones that FileIO used indirectly, `QuartzImageIO` etc.

This format doesn't do that and installed everything upfront.

Maybe that's a Pkg bug though

**Comment by timholy** [comment]
Hmm, interesting. I don't see why they'd be different, but I haven't dug into it.

**Comment by IanButterworth** [comment]
Me neither. I'll try to come up with a MWE for Pkg

**Comment by KristofferC** [comment]
> sometime during test execution it complained about some of the test deps not being installed

That sounds weird.. Would be good to track that down indeed.

**Comment by IanButterworth** [comment]
Closing as stale

**Pull request closed without merging**
