### PR TITLE
Add bounds and fix tests

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by timholy** [comment]
Hmm, on Julia 1.3 appveyor I am getting
```
could not load library "zlib1"
│ %1 is not a valid Win32 application.
```
https://ci.appveyor.com/project/timholy/imageview-jl/builds/29282138/job/g213wh2gy95mp22r

Any ideas, @staticfloat or @giordano?

**Comment by giordano** [comment]
It looks like WinRPM needs to be updated, that library on Windows is now called libz, like any other operating system, see for example https://github.com/JuliaIO/GZip.jl/pull/84

**Comment by giordano** [comment]
Or maybe we need a new release of libz https://github.com/BioJulia/Libz.jl/pull/66

**Comment by timholy** [comment]
Thanks @giordano! There's a note on the Libz.jl README suggesting https://github.com/bicycle1885/CodecZlib.jl instead.

**Pull request merged**
