### PR TITLE
[WIP] add CI to OSX

### PR DESCRIPTION
**Pull request by johnnychen94**
cont. https://github.com/JuliaImages/ImageView.jl/pull/170

### CODE REVIEW

**Comment by johnnychen94** [comment]
this's strange, I'll try it tomorrow @timholy

**Comment by johnnychen94** [comment]
In https://travis-ci.org/JuliaImages/ImageView.jl/requests it says `Could not parse JuliaImages/ImageView.jl/.travis.yml@a9ff4886c729fd7d`, which is caused by an incorrect comment place, the following changes fix it. 

```diff
+# install specific glib version; see https://github.com/JuliaGraphics/Cairo.jl/issues/271
before_install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then 
-        # install specific glib version; see https://github.com/JuliaGraphics/Cairo.jl/issues/271
        brew install --verbose --build-from-source 'https://raw.githubusercontent.com/Homebrew/homebrew-core/05871cb0394f78ef25a5c1c071456d0f1e4be4fe/Formula/glib.rb' ;
        ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok; )&
    fi
```

**Comment by johnnychen94** [comment]
`Cairo` is successfully built, any ideas why it fails on `TestImages`?

**Comment by johnnychen94** [comment]
@timholy Here's the minimal working script for you to work on :) There are some tests fail, which is out of my ability.

```yml
language: julia
sudo: true
dist: trusty
os: osx
julia:
  - 1.0

script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
    - $TESTCMD -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
```

**Comment by timholy** [comment]
Thanks for trying! Multiplatform support can be tricky.

Given the frustrations with Cairo/Gtk, this may be extra motivation to develop the browser-based version of ImageView.

**Pull request closed without merging**
